# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='summary_images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=600)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ari.Email')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ari.Image')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ari.URL'),
        ),
    ]
