# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ari', '0003_auto_20171225_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(default='arikanevsky@gmail.com', max_length=254),
        ),
    ]
