# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ari', '0004_auto_20171226_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='summary_images/Y/M/D/no_img.jpg', upload_to='summary_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ari.Email'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ari.Image'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ari.URL'),
        ),
    ]
