# Generated by Django 2.0 on 2017-12-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ari', '0005_auto_20171226_0059'),
    ]

    operations = [
        migrations.RenameModel('Summary', 'Page')
    ]
