# Generated by Django 2.0 on 2017-12-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ari', '0006_auto_20171226_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='page_images/Y/M/D/no_img.jpg', upload_to='page_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='page',
            name='summary',
            field=models.TextField(),
        ),
    ]
