# Generated by Django 2.0 on 2018-01-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ari', '0008_auto_20180104_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default='insert summary')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ari.Summary'),
        ),
    ]
