# Generated by Django 2.0 on 2018-01-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ari', '0009_auto_20180104_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='Y/M/D/no_img.jpg', upload_to='%Y/%m/%d'),
        ),
    ]
